//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace henriettasschool1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int AssignmentsID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public System.DateTime DateOfSubmission { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Courses { get; set; }
    }
}
