//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace henriettasschool1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CoursesID { get; set; }
        public string Title { get; set; }
        public string TypeOfCourse { get; set; }
        public System.DateTime DateOfStart { get; set; }
        public System.DateTime DateOfEnd { get; set; }
        public string Assignments { get; set; }
    }
}
