//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace henriettasschool1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eriettaDB2Entities : DbContext
    {
        public eriettaDB2Entities()
            : base("name=eriettaDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<Question1> Question1 { get; set; }
        public virtual DbSet<Question2> Question2 { get; set; }
        public virtual DbSet<Question3> Question3 { get; set; }
        public virtual DbSet<Question4> Question4 { get; set; }
        public virtual DbSet<Question5> Question5 { get; set; }
        public virtual DbSet<Question6> Question6 { get; set; }
        public virtual DbSet<Question7> Question7 { get; set; }
        public virtual DbSet<Question8> Question8 { get; set; }
    }
}
